name: Python CI

#workflow
on:
  push:
    branches:
    # en cas de push sur la branche principale
      - main  
  pull_request:
    branches:
    # en cas de pull request sur la branche principale
      - main  

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    # Config Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.9'  

    # Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff

    # Vérification du formatage 
    - name: Run Black
      run: black --check .

    # Vérification avec Ruff
    - name: Run Ruff
      run: ruff check .
